EmpleadosMVC/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmpleadosMVC.Models;
using EmpleadosMVC.Enums;
using Microsoft.AspNetCore.Cors;

namespace EmpleadosMVC.Controllers
{   
    public class EmpleadosController : Controller
    {
        private EmpleadoDBContext db = new EmpleadoDBContext();

        // GET: Empleados
        public ActionResult Index(
            
            string BuscarCategoria, 
            string BuscarNombre,
            string BuscarAntiguedad, 
            string BuscarEdad,
            int page = 0,
            ESize MenorMayor = 0,
            ECol OrderBy = 0
            )
        {
            int pageSize = 10;
            var antiguedad=0;
            try 
            {
                antiguedad = Convert.ToInt32(BuscarAntiguedad);
            }
            catch { }
            var ListaCategoria = new List<string>();

            var ConsultaCategoria = from e in db.Empleados orderby e.Categoria select e.Categoria;
            ListaCategoria.AddRange(ConsultaCategoria.Distinct());

            ViewBag.NextPage = (page + 1).ToString();
            ViewBag.PrevPage = (page - 1).ToString();
            ViewBag.page = (page).ToString();
            ViewBag.NextPageBool = true;

            ViewBag.EmpleadoCategoria = new SelectList(ListaCategoria);
            ViewBag.MenorMayor = new SelectList(new List<string> { ESize.Menor.ToString(), ESize.Mayor.ToString() });
            ViewBag.OrderBy = new SelectList(new List<string> 
            { 
                ECol.Nombre.ToString(),
                ECol.Antiguedad.ToString(), 
                ECol.Edad.ToString(),
                ECol.Categoria.ToString()
            });
           
            var empleadosTots = from e in db.Empleados select e;

            var empleadosFiltrats = filtrarPaginar(empleadosTots, BuscarNombre, BuscarEdad, antiguedad, BuscarCategoria, page, pageSize, MenorMayor, OrderBy);

            if (empleadosFiltrats.Count() + ((page)* pageSize) >= empleadosTots.Count())
                ViewBag.NextPageBool = false;
            return View(empleadosFiltrats);
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        //API
        // GET:ENDPOINT Empleados/allAPI
        [EnableCors("origins: *, headers: *, methods: *")]
        public string allAPI()
        {
            IList<Empleado> empleados = db.Empleados.ToList();
            return "Method(" + empleadoToJson(empleados) + ")";
        }

        //API
        // GET:ENDPOINT Empleados/DetailsAPI/5
        [EnableCors("origins: *, headers: *, methods: *")]
        public string DetailsAPI(int? id)
        {
            if (id != null)
            {
                Empleado empleado = db.Empleados.Find(id);
                if(empleado != null)
                    return "Method(" + empleadoToJson(empleado) + ")";
            }
            return "Method({ })";
        }

        //API
        // GET:ENDPOINT Empleados/DetailsAPI/5
        [EnableCors("origins: *, headers: *, methods: *")]
        public string DeleteAPI(int? id)
        {
            Empleado empleado = db.Empleados.Find(id);
            db.Empleados.Remove(empleado);
            db.SaveChanges();
            return "Method({ })";
        }

        //API
        // GET:ENDPOINT Empleados/EditAPI/5
        //[ValidateAntiForgeryToken]
        [HttpGet]//post o put me dan error de CORS
        [EnableCors("origins: *, headers: *, methods: *")]
        public void EditAPI( Empleado empleado)
        {
            if (empleado.ID != 0)
            {
                empleado = llenarCamposNull(empleado);

                if (validacionLogicaEdadAntiguedad(empleado.Edad, empleado.Antiguedad))
                {
                    var query = (from a in db.Empleados
                                 where a.ID == empleado.ID
                                 select a).FirstOrDefault();

                    query.Nombre = empleado.Nombre;
                    query.Edad = empleado.Edad;
                    query.Antiguedad = empleado.Antiguedad;
                    query.Categoria = empleado.Categoria;

                    db.SaveChanges();
                }
            }
        }

        // GET: Empleados/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateError()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateError([Bind(Include = "ID,Nombre,Antiguedad,Edad,Categoria")] Empleado empleado)
        {
            if (!ModelState.IsValid)
            {
                return View(empleado);
            }

            if (!validacionLogicaEdadAntiguedad(empleado.Edad, empleado.Antiguedad))
            {
                return RedirectToAction("CreateError");
            }

            db.Empleados.Add(empleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool validacionLogicaEdadAntiguedad(int edad, int antiguedad) 
        {
            return edad - 18 >= antiguedad;
        }

        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Antiguedad,Edad,Categoria")] Empleado empleado)
        {
            if (!ModelState.IsValid)
            {
                return View(empleado);
            }
            
            if (!validacionLogicaEdadAntiguedad(empleado.Edad, empleado.Antiguedad))
            {
                return RedirectToAction("CreateError");
            }

            db.Empleados.Add(empleado);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpGet]
        public ActionResult CreateRandom()
        {
            var empleadoRnd = new Empleado().EmpleadoRnd(db);
            db.Empleados.Add(empleadoRnd);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Antiguedad,Edad,Categoria")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                if(validacionLogicaEdadAntiguedad(empleado.Edad, empleado.Antiguedad)) 
                { 
                    db.Entry(empleado).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleado empleado = db.Empleados.Find(id);
            db.Empleados.Remove(empleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            
            base.Dispose(disposing);
        }

        private IQueryable<Empleado> filtrarPaginar(
            IQueryable<Empleado> Empleados,
            string BuscarNombre,
            string BuscarEdad,
            int BuscarAntiguedad,
            string BuscarCategoria ,
            int page,
            int pageSize,
            ESize MenorMayor = 0,
            ECol OrderBy = 0
            ) 
        {
            int pgSkip = page * pageSize;

            //Edad filter
            if (!string.IsNullOrEmpty(BuscarEdad))
            {
                Empleados = Empleados.Where(e => e.Edad.Equals(BuscarEdad));
            }

            //Nombre filter
            if (!string.IsNullOrEmpty(BuscarNombre))
            {
                Empleados = Empleados.Where(e => e.Nombre.Contains(BuscarNombre));
            }

            //Categoria filter

EmpleadosMVC/Views/Empleados/Create.cshtml
@model EmpleadosMVC.Models.Empleado
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Antiguedad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Antiguedad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Antiguedad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" }, maxlength = "20"})
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmpleadosMVC/Views/Empleados/CreateError.cshtml
@model EmpleadosMVC.Models.Empleado

@{
    ViewBag.Title = "CreateError";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Antiguedad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Antiguedad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Antiguedad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h4 class="text-danger">El empleado no se ha podido crear por una incoherencia en los datos. Resivalo</h4>
</hgroup>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmpleadosMVC/Views/Empleados/CreateRandom.cshtml
@model EmpleadosMVC.Models.Empleado

@{
    ViewBag.Title = "CreateRandom";
}

<h2>CreateRandom</h2>

<div>
    <h4>Empleado Random creado</h4>
    <hr />

</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

EmpleadosMVC/Views/Empleados/Delete.cshtml
@model EmpleadosMVC.Models.Empleado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Antiguedad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Antiguedad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EmpleadosMVC/Views/Empleados/Details.cshtml
@model EmpleadosMVC.Models.Empleado

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Antiguedad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Antiguedad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EmpleadosMVC/Views/Empleados/Edit.cshtml
@model EmpleadosMVC.Models.Empleado

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Antiguedad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Antiguedad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Antiguedad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmpleadosMVC/Views/Empleados/Index.cshtml
@model IEnumerable<EmpleadosMVC.Models.Empleado>

@{
    ViewBag.Title = "Index";
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<h2>Index</h2>
<p>

    @using (Html.BeginForm("Index", "Empleados", FormMethod.Get))
    {
    <p>
        <table class="table">
            <tr>
                <th>
                    Nombre: @Html.TextBox("BuscarNombre")
                </th>
                <th>
                    Categoria:@Html.DropDownList("EmpleadoCategoria", "Todas")
                </th>
                <th>
                    Antiguedad:@Html.DropDownList("MenorMayor", "") @Html.TextBox("BuscarAntiguedad")
                </th>
                <th>
                    Edad:@Html.TextBox("BuscarEdad")
                </th>
                <th>
                    <input class="btn btn-default alert-info" type="submit" value="Buscar" />
                </th>
            </tr>

            <tr>
                <th id="orderBy">
                    OrderBy:@Html.DropDownList("OrderBy", "")
                </th>
            </tr>
        </table>
    </p>
}




    <p>
        @Html.ActionLink("Create New ", "Create") | @Html.ActionLink(" Create New Random", "CreateRandom")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Antiguedad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Antiguedad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </table>
    
    <p>
        @if (ViewBag.page != "0")
        {
            @Html.ActionLink((string)@ViewBag.PrevPage, "index", new { page = ViewBag.PrevPage }, new { @class = "btn btn-default" })
        }
        @Html.ActionLink((string)@ViewBag.page, "index", new { page = ViewBag.page }, new { @class = "btn btn-default btn-info" })
        @if (ViewBag.NextPageBool) { 
            @Html.ActionLink((string)@ViewBag.NextPage, "index", new { page = ViewBag.NextPage }, new { @class = "btn btn-default" })
        }
    </p>